#!/bin/bash

# debug
# set -xe

# VARS
PROVIDER="$1"
MODULE_NAME="$2"
_DIR=$(pwd)
MODULES="modules"
README="README.md"
MAIN="main.tf"
OUTPUT="outputs.tf"
VERSION="versions.tf"
VARIABLES="variables.tf"


function check_exists_dir() {
    [[ -e $_DIR/terraform-${PROVIDER}-${MODULE_NAME}/${MODULES} ]]
}

function create_dir_module() {
    mkdir -p terraform-${PROVIDER}-${MODULE_NAME}/${MODULES}
}

function create_structure_module() {
    # Create README.md
    touch terraform-${PROVIDER}-${MODULE_NAME}/${README}

    # Create terraform files in root folder
    touch terraform-${PROVIDER}-${MODULE_NAME}/${MAIN} terraform-${PROVIDER}-${MODULE_NAME}/${OUTPUT} terraform-${PROVIDER}-${MODULE_NAME}/${VARIABLES} terraform-${PROVIDER}-${MODULE_NAME}/${VERSION}

    # Create module folder
    mkdir -p terraform-${PROVIDER}-${MODULE_NAME}/${MODULES}/${MODULE_NAME}

    # Create terraform files in modules folder
    touch terraform-${PROVIDER}-${MODULE_NAME}/${MODULES}/${MODULE_NAME}/${README} terraform-${PROVIDER}-${MODULE_NAME}/${MODULES}/${MODULE_NAME}/${MAIN} terraform-${PROVIDER}-${MODULE_NAME}/${MODULES}/${MODULE_NAME}/${OUTPUT} terraform-${PROVIDER}-${MODULE_NAME}/${MODULES}/${MODULE_NAME}/${VARIABLES}
}

function terraform_structure_module()
{   

    if check_exists_dir; then
        echo "This directory already exists"
    else
        create_dir_module

        if [[ -e $PWD/terraform-${PROVIDER}-${MODULE_NAME}/${MODULES} ]]; then
            create_structure_module
        fi

    fi
}

terraform_structure_module
